apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-rollout
  namespace: default
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
      autoPromotionEnabled: false # Automatically promote after a new version
  selector:
    matchLabels:
      app: bluegreen-app
  template:
    metadata:
      labels:
        app: bluegreen-app
    spec:
      containers:
      - name: app
        image: nginx:1.23.5 # Replace with your application image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-active
  namespace: default
spec:
  type: NodePort
  selector:
    app: bluegreen-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080 # Replace with your desired NodePort range
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-preview
  namespace: default
spec:
  type: NodePort
  selector:
    app: bluegreen-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
