name: Update Rollout Image Tag with Commit ID

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: self-hosted

    steps:
    - name: Checkout nginx Repository
      uses: actions/checkout@v3
      with:
        repository: Mo7amedMostafa/nginx
        token: ${{ secrets.GITHUB_TOKEN }}
        path: deploy

    - name: Checkout deploy Repository
      uses: actions/checkout@v3
      with:
        repository: Mo7amedMostafa/deploy
        token: ${{ secrets.GITHUB_TOKEN }}
        path: deploy2

    - name: Update Image Tag in rollout.yaml
      run: |
        cd deploy2
        COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
        sed -i "s|image: mo7amedmostafa/nginx:.*|image: mo7amedmostafa/nginx:${COMMIT_ID}|g" ./rollout/rollout.yaml
    
    - name: Build Docker Image for nginx
      run: |
        cd deploy/deploy/
        COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t nginx:${COMMIT_ID} .
        docker tag nginx:${COMMIT_ID} mo7amedmostafa/nginx:${COMMIT_ID}
        # echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push mo7amedmostafa/nginx:${COMMIT_ID}

    - name: Commit and Push Changes to deploy Repository
      run: |
        cd deploy2
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin git@github.com:Mo7amedMostafa/deploy.git
        git add rollout/rollout.yaml
        git commit -m "Update image tag to commit ${{ github.sha }}"
        git push origin main

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
