name: Update Rollout Image Tag with Commit ID

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout nginx Repository
      uses: actions/checkout@v3

    - name: Checkout deploy Repository
      uses: actions/checkout@v3
      with:
        repository: Mo7amedMostafa/deploy
        token: ${{ secrets.GITHUB_TOKEN }}
        path: deploy

    - name: Update Image Tag in rollout.yaml
      run: |
        COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
        sed -i "s|image: argoproj/rollouts-demo:.*|image: argoproj/rollouts-demo:${COMMIT_ID}|g" deploy/rollout/rollout.yaml

    - name: Commit and Push Changes to deploy Repository
      run: |
        cd deploy
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_PAT }}@github.com/Mo7amedMostafa/deploy.git
        git add rollout/rollout.yaml
        git commit -m "Update image tag to commit ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
