name: Update Rollout Image Tag with Commit ID

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Image Tag in rollout.yaml
      run: |
        COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
        sed -i "s|image: argoproj/rollouts-demo:.*|image: argoproj/rollouts-demo:${COMMIT_ID}|g" rollout/rollout.yaml

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add rollout/rollout.yaml
        git commit -m "Update image tag to commit ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
